import Shop from '@/app/Components/Shop'
import React from 'react'

export const metadata = {
  title: "Shop Page | Next App",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <Shop/>
    </>
  )
}
