import '../assets/css/style.css'
import Layout from '../Components/Common/Layout';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
