
import Image from "next/image";
import Home from "../Components/Home";
import { menProductsData, womenProductsData } from "../APISevices/APIServices";

export const metadata = {
  title: "Home Page | Next App",
  description: "Generated by create next app",
};

export default async function page() {

  var womenData = await womenProductsData();
  var menData = await menProductsData();

  return (
    <>
      <Home womenProducts={womenData} menProducts={menData}/>
    </>
  );
}
